<?php

namespace AppBundle\Repository;

/**
 * PrizesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrizesRepository extends \Doctrine\ORM\EntityRepository
{
}
