<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WinningRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WinningRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllWinnings($id)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT w FROM AppBundle:Winning w WHERE w.userId = $id AND w.status=true"
            )
            ->getResult();
    }
}
