<?php

namespace AppBundle\Repository;

/**
 * WinningRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WinningRepository extends \Doctrine\ORM\EntityRepository
{
}
